# Var recoding for summary stats

recode_var = function(x){
  recode(x,
         antiguedad = 'Tenure',
         exitoso = 'Success',
         salario_diario = 'Wage',
         mujer = 'Woman',
         prob_ganar = 'Probability of Winning',
         cantidad_ganar ='Expected compensation',
         prob_mayor = 'More than 75%',
         cant_mayor = 'More than 180 days',
         carta_renuncia = 'Resignation letter',
         c_min_total = 'Minimum legal entitlement',
         prob_num = 'Exact probability answer',
         prob_coarse = 'At least coarse probability answer',
         cantidad_num = 'Exact amount answer',
         cantidad_coarse = 'At least coarse amount answer',
         conflicto_arreglado = 'Solved conflict',
         entablo_demanda = 'Sued',
         se_registro_el_acuerdo_ante_la_junta = 'Registered settlement at court',
         tiempo_arreglo = 'Time to solve',
         sabemos_cantidad = 'We know settlement amount',
         sabemos_fecha_arreglo = 'We know settlement date',
         ha_hablado_con_abogado_publico = 'Talked to public lawyer',
         ha_hablado_con_abogado_privado = 'Talked to private lawyer',
         firmo_carta_poder = 'Signed power of attorney',
         tramito_citatorio = 'Got letter of appointment',
         sigue_buscando_alternativas_de_abogados_privados = 'Keeps looking for private lawyers',
         piensa_hacer_algo_respecto_al_despido = 'Wants to do something',
         update_prob = 'Relative probability update',
         update_comp = 'Relative compensation update',
         switched_prob = 'Reduced probability (crossed cutoff)',
         switched_comp = 'Reduced compensation (crossed cutoff)',
         mas_secundaria = 'More than Junior High',
         nivel_de_felicidad = 'Happiness',
         demando_con_abogado_publico = 'Sued w. public lawyer',
         enojo_con_la_empresa = 'Anger',
         busca_trabajo = 'Looking for a job',
         visitas_a_la_junta_y_procuraduria = 'Visits to court',
         ultimos_3_meses_ha_dejado_de_pagar_servicio_basico = 'Could not pay basic service (3M)',
         ultimos_3_meses_le_ha_faltado_dinero_para_comida = 'Could not buy food (3M)',
         ultimo_mes_alguien_del_hogar_a_comprado_casa_o_terreno_o_vehiculo = 'Bought house, land or vehicle (1M)',
         ultimo_mes_alguien_del_hogar_a_comprado_electrodomestico_o_dispositivo_electronico = 'Bought elecronic appliances (1M)',
         asistio_cita = 'Went to conciliation meeting',
         cant_rec_sueldo = 'Unpaid wages',
         jornada_diurna = 'Daytime shift',
         dummy_desc_ob = 'Holiday bonus',
         dummy_desc_sem = 'Weekly rest bonus',
         dummy_prima_dom = 'Sunday bonus',
         dummy_reinst = 'Reinstatement',
         dummy_sarimssinfo = 'IMSS/INFONAVIT',
         horas_sem = 'Weekly hours',
         muy_enojado = 'Very angry',
         top_demandado = 'Top sue')
}


# Names for Google Forms data
names_gftodf <- c('timestamp',
                  'nivel_de_felicidad',
                  'conflicto_arreglado',
                  'reinstalacion',
                  'entablo_demanda1',
                  'demando_con_abogado_privado',
                  'monto_del_convenio',
                  'fecha_arreglo',
                  'se_registro_el_acuerdo_ante_la_junta',
                  'entablo_demanda2',
                  'demando_con_abogado_privado2',
                  'entablo_demanda3',
                  'fecha_de_demanda',
                  'demando_con_abogado_privado3',
                  'como_lo_consiguio',
                  'cuota_por_iniciar_juicio',
                  'porcentaje',
                  'especifique_cobro2',
                  'donde_lo_contacto',
                  'tramito_citatorio',
                  'pidio_ser_reinstalado',
                  'cuantos_dias_de_salario_corresponde_la_indem_const',
                  'nivel_de_satisfaccion_abogado',
                  'quiere_cambiar_abogado',
                  'enojo_con_la_empresa',
                  'prob_num_survey',
                  'cantidad_num_survey',
                  'que_elemento_es_el_mas_importante_al_elaborar_expectativas_1',
                  'minimo_que_aceptaria_para_solucionar_conflicto',
                  'ultimos_3_meses_ha_dejado_de_pagar_servicio_basico',
                  'ultimos_3_meses_le_ha_faltado_dinero_para_comida',
                  'ultimo_mes_base',
                  'trabaja_actualmente',
                  'comparacion_con_el_trabajo_anterior',
                  'busca_trabajo',
                  'probabilidad_de_que_encuentre_trabajo_en_los_prox_3_meses',
                  'tiempo_arreglar_asunto',
                  'especifique_cobro',
                  'asistio_patron_a_la_cita',
                  'X40',
                  'mas_o_menos_de_75',
                  'mas_o_menos_de_6_meses_de_sueldo',
                  'promedio_de_horas_en_traslado',
                  'que_elemento_es_el_mas_importante_al_elaborar_expectativas_2',
                  'minimo_que_aceptaria_para_solucionar_conflicto2',
                  'id_actor',
                  'fecha_ultimo_intento_encuesta',
                  'nombre_encuestador',
                  'status_encuesta',
                  'probabilidad_de_ganar',
                  'monto_que_espera_recibir',
                  'actitud_encuestado')



names_gftodf_2w<- c('timestamp',
                    'id_actor',
                    'fecha_ultimo_intento_encuesta',
                    'nombre_encuestador',
                    'status_encuesta',
                    'conflicto_arreglado',
                    'reinstalacion',
                    'dice_cantidad',
                    'monto_del_convenio',
                    'fecha_del_arreglo',
                    'se_registro_el_acuerdo_ante_la_j',
                    'ha_hablado_con_abogado_publico',
                    'tramito_citatorio',
                    'fecha_de_la_cita_procu',
                    'entablo_demanda',
                    'ha_hablado_con_abogado_privado',
                    'como_lo_encontro',
                    'firmo_carta_poder',
                    'esquema_de_pago',
                    'esquema_de_cobro_porcentaje',
                    'porcentaje',
                    'esquema_de_cobro_pago_para_inici',
                    'cuota_por_iniciar_juicio',
                    'sigue_buscando_alternativas_de_a',
                    'tramito_alguna_cita_de_conciliac',
                    'fecha_de_la_cita_junta',
                    'dummy_encuestador',
                    'piensa_hacer_algo_respecto_al_de',
                    'sabe_prob',
                    'probabilidad_de_ganar',
                    'mas_o_menos_de_75',
                    'sabe_monto',
                    'monto_que_espera_recibir',
                    'mas_o_menos_de_6_meses_de_sueldo',
                    'ha_iniciado_una_demanda_laboral_',
                    'hace_cuanto_anios',
                    'gano_el_juicio',
                    'grado_de_estudios')

rename_opm = function(df){
  rename(df,
         id_opm = q_a,
         fecha_ultimo_intento_encuesta = q_b,
         nombre_encuestador = q_c,
         status_encuesta = q_d,
         nivel_de_felicidad = q_1,
         conflicto_arreglado = q_2,
         reinstalacion = q2a,
         entablo_demanda_1 = q2a_i,
         demando_con_abogado_publicoo_1 = q2a_i_i,
         monto_del_convenio = q2a_ii,
         fecha_arreglo = q2a_iii,
         se_registro_el_acuerdo_ante_la_junta = q2a_iv,
         entablo_demanda_2 = q_3,
         fecha_de_demanda = q_3a,
         demando_con_abogado_publico_2 = q_3b,
         donde_lo_contacto = q_3b_i,
         tramito_citatorio = q_3b_ii,
         asistio_patron_a_la_cita = q_3b_ii_i,
         como_lo_consiguio = q_3b_iii,
         esquema_de_cobro_pago_para_iniciar_juicio = q_3b_iv,
         porcentaje = q_3b_v,
         esquema_de_cobro_otro = q_3b_vi,
         especifique_cobro = q_3b_vi_i,
         pidio_ser_reinstalado = q3c,
         cuantos_dias_de_salario_corresponde_la_indem_const = q3d,
         nivel_de_satisfaccion_abogado = q3e,
         quiere_cambiar_abogado = q3f,
         enojo_con_la_empresa = q3g,
         probabilidad_de_ganar = q3h,
         mas_o_menos_de_75 = q3h_i,
         monto_que_espera_recibir = q3i,
         mas_o_menos_de_6_meses_de_sueldo = q3i_i,
         que_elemento_es_el_mas_importante_al_elaborar_expectativas = q3j,
         minimo_que_aceptaria_para_solucionar_conflicto = q3k,
         ultimos_3_meses_ha_dejado_de_pagar_servicio_basico = q4,
         ultimos_3_meses_le_ha_faltado_dinero_para_comida = q5,
         ultimo_mes_1 = q6_o1,
         ultimo_mes_2 = q6_o2,
         ultimo_mes_3 = q6_o3,
         ultimo_mes_4 = q6_o4,
         trabaja_actualmente = q7,
         comparacion_con_el_trabajo_anterior = q7a,
         busca_trabajo = q7b,
           probabilidad_de_que_encuentre_trabajo_en_los_prox_3_meses = q7b_i,
         tiempo_arreglar_asunto = q8,
         tiempo_trayecto_h = q9hh, 
         tiempo_trayecto_m = q9mm)
}
